tabWidth: 4
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: true
arrowParens: always
proseWrap: always
endOfLine: lf
plugins:
  - prettier-plugin-organize-imports
  - prettier-plugin-packagejson